blank_issues_enabled: false

contact_links:
  - name: ğŸ™ Help and support
    url: https://github.com/willpinha/shoelace-collection/discussions/categories/help-and-support
    about: Ask the community for help
