contact_links:
  - name: Add new UI example 
    about: Add a new UI example to the collection
    url: https://github.com/willpinha/daisy-collection/blob/master/CONTRIBUTING.md#guide-to-add-a-new-ui-example
